<?php
$this->headTitle('Add Account');
$this->mainMenu()->setActiveItemId('Admin');
$this->pageBreadcrumbs()->setItems([
		'Home'=>$this->url('home'),
		'admin'=>$this->url('myauth', ['action'=>'company']),
		'Chart of Accounts'=>$this->url('mychart', ['action'=>'index'])
]);

$form->get('account')->setAttributes([
		'class'=>'form-control',
		'placeholder'=>''
]);
$form->get('description')->setAttributes([
		'class'=>'form-control',
		'placeholder'=>''
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Add Account</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('account')); ?>
            <?= $this->formElement($form->get('account')); ?>
            <?= $this->formElementErrors($form->get('account')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>                  
        </div>
                    
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>  
    
    <div class="col-md-6">
    	<h3>Chart of Accounts</h3>
		 <table class="table table-striped">
		
		    <?php foreach ($accounts as $acc): ?>
		    
			    <tr>
			    	<td><?= $this->escapeHtml($acc->getAccount()); ?></td>
			        <td><?= $this->escapeHtml($acc->getDescription()); ?></td>
			    </tr>
		        
		    <?php endforeach; ?>   
		    
		</table>   	
    </div>  
</div>   