<?php
$this->headTitle('Admin');
$this->mainMenu()->setActiveItemId('Admin');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
			'Admin'=>$this->url('myauth', ['action'=>'company']),
            ]);
?>

<h2>Chart of Accounts</h2>

<p><a href="<?= $this->url('mychart',['action' => 'add']);?>" class="btn btn-default">NEW ACCOUNT</a>
</p>
<table class="table table-striped">

    <?php foreach ($accounts as $acc): ?>
    
	    <tr>
	    	<td><?= $this->escapeHtml($acc->getAccount()); ?></td>
	        <td><?= $this->escapeHtml($acc->getDescription()); ?></td>
	        <td><?php echo '<a href="'.$this->url('mychart', ['action'=>'edit','id' => $acc->getId()]).'">Edit</a>';
	               
	        ?></td>
	    </tr>
        
    <?php endforeach; ?>   
    
</table>


<p><a href="/logout">LOGOUT</a></p>