<?php
$this->headTitle('Add Currency');
$this->mainMenu()->setActiveItemId('Admin');
$this->pageBreadcrumbs()->setItems([
		'Home'=>$this->url('home'),
		'admin'=>$this->url('myauth', ['action'=>'company']),
		'Enterprise parameters'=>$this->url('myenterprise', ['action'=>'index'])
]);

$form->get('name')->setAttributes([
		'class'=>'form-control',
		'placeholder'=> ''
]);
$form->get('amount')->setAttributes([
		'class'=>'form-control',
		'placeholder'=> ''
]);

$form->get('debit')->setAttributes([
		'class'=>'form-control',
		'placeholder'=> ''
]);
$form->get('credit')->setAttributes([
		'class'=>'form-control',
		'placeholder'=> ''
]);


$form->get('default')->setAttributes([
		'class'=>'form-control',
		'placeholder'=> ''
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Add VAT</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('amount')); ?>
            <?= $this->formElement($form->get('amount')); ?>
            <?= $this->formElementErrors($form->get('amount')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('debit')); ?>
            <?= $this->formElement($form->get('debit')); ?>
            <?= $this->formElementErrors($form->get('debit')); ?>                  
        </div>
         <div class="form-group">
            <?= $this->formLabel($form->get('credit')); ?>
            <?= $this->formElement($form->get('credit')); ?>
            <?= $this->formElementErrors($form->get('credit')); ?>                  
        </div>                 
        <div class="form-group">
            <?= $this->formLabel($form->get('default')); ?>
            <?= $this->formElement($form->get('default')); ?>
            <?= $this->formElementErrors($form->get('default')); ?>                  
        </div>
                                      
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>  
    

</div>   