<?php
$this->headTitle('Add Address');
$this->mainMenu()->setActiveItemId('addresses');
$this->pageBreadcrumbs()->setItems([
		'Home'=>$this->url('home'),
		'Manage Company'=>$this->url('myauth',['action'=>'company']),
		'Manage Addresses' => $this->url('myauth',['action'=>'addresses'])
]);


$form->get('address_name')->setAttributes([
		'class'=>'form-control',
		'placeholder'=>''
]);
$form->get('address')->setAttributes([
		'class'=>'form-control',
		'placeholder'=>'Company Address'
]);

$form->get('postcode')->setAttributes([
		'class'=>'form-control'
]);
$form->get('city')->setAttributes([
		'class'=>'form-control'
]);

$form->get('country')->setAttributes([
		'class'=>'form-control'
]);

$form->get('phone')->setAttributes([
		'class'=>'form-control'
]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Add Address</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('address_name')); ?>
            <?= $this->formElement($form->get('address_name')); ?>
            <?= $this->formElementErrors($form->get('address_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('address')); ?>
            <?= $this->formElement($form->get('address')); ?>
            <?= $this->formElementErrors($form->get('address')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('postcode')); ?>
            <?= $this->formElement($form->get('postcode')); ?>
            <?= $this->formElementErrors($form->get('postcode')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('city')); ?>
            <?= $this->formElement($form->get('city')); ?>
            <?= $this->formElementErrors($form->get('city')); ?>                  
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('country')); ?>
            <?= $this->formElement($form->get('country')); ?>
            <?= $this->formElementErrors($form->get('country')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('phone')); ?>
            <?= $this->formElement($form->get('phone')); ?>
            <?= $this->formElementErrors($form->get('phone')); ?>                  
        </div>
                 
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   