<?php
$this->headTitle('Company Settings');
$this->mainMenu()->setActiveItemId('company');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('myauth'),
            'Company Settings'=>$this->url('myauth', ['action'=>'company'])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>Company Details</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($company->getId()) ?></td>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($company->getCompanyName()) ?></td>
            </tr>
            <tr>
                <th>Identification:</th>
                <td><?= $this->escapeHtml($company->getCompanyIdentification()) ?></td>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($company->getDateCreated()->format('Y-m-d H:i:s')) ?></td>
            </tr>
            <tr>
                <th>Start of Fiscal year:</th>
                <td><?= $this->escapeHtml($company->getStart()) ?></td>
            </tr>
            <tr>
                <th>End of fiscal year:</th>
                <td><?= $this->escapeHtml($company->getEnd()) ?></td>
            </tr>  
            <tr>
                <th>URL:</th>
                <td><?= $this->escapeHtml($company->getUrl()) ?></td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
	<p><a href="<?= $this->url('myauth', ['action'=>'addresses']); ?>" class="btn btn-info">Access Company Addresse(s)</a></p>
    <p><a href="<?= $this->url('myauth', ['action'=>'updates']); ?>" class="btn btn-danger">Access Status / Type / Tax / Profit</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
		<a href="<?= $this->url('myauth', ['action'=>'editCompany']); ?>" class="btn btn-primary">Edit details</a>.
	</div>
</div>
