<?php
$this->headTitle('View User');
$this->mainMenu()->setActiveItemId('users');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('myauth'),
            'View User'=>$this->url('myauth', ['action'=>'view', 'id'=>$user->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getUseremail()) ?></td>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?= $this->escapeHtml($user->getUsername()) ?></td>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()->format('Y-m-d H:i:s')) ?></td>
            </tr>

        </table>
    </div>
</div>
Contact GitHub API Training Shop Blog About
